# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170804_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='adult_content',
        ),
        migrations.RemoveField(
            model_name='show',
            name='nudity',
        ),
        migrations.RemoveField(
            model_name='show',
            name='strong_language',
        ),
        migrations.AddField(
            model_name='genre',
            name='warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='show',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='shows', to='catalog.Genre'),
        ),
    ]
