# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170805_0821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='paymenttype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['show', 'date_time']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['show', 'source']},
        ),
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together=set([('show', 'date_time')]),
        ),
    ]
