# Generated by Django 2.0.2 on 2018-02-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_auto_20180224_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='long_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
