# Generated by Django 2.0.2 on 2018-02-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_show_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
