# Generated by Django 2.0.2 on 2018-02-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_auto_20180225_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['show', 'date', 'time']},
        ),
        migrations.RemoveField(
            model_name='performance',
            name='date_time',
        ),
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together={('show', 'date', 'time')},
        ),
    ]
