# Generated by Django 2.0.2 on 2018-02-28 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_boxoffice'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='box_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venues', to='program.BoxOffice'),
        ),
    ]
