# Generated by Django 2.0.2 on 2018-03-03 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_venue_box_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='ticketed',
        ),
        migrations.AddField(
            model_name='show',
            name='theatrefest_ID',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_ticketed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='venue',
            name='box_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venues', to='program.BoxOffice'),
        ),
    ]
