# Generated by Django 2.0.2 on 2018-04-03 12:53

from django.db import migrations, models
import django.db.models.deletion
import program.models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_auto_20180303_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('image', models.ImageField(blank=True, default='', upload_to=program.models.get_image_filename)),
            ],
            options={
                'ordering': ['show', 'name'],
            },
        ),
        migrations.AddField(
            model_name='show',
            name='html_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='showimage',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='program.Show'),
        ),
        migrations.AlterUniqueTogether(
            name='showimage',
            unique_together={('show', 'name')},
        ),
    ]
