# Generated by Django 2.0.2 on 2018-04-07 13:55

from django.db import migrations, models
import django.db.models.deletion
import program.models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_auto_20180403_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxOfficeSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.CharField(max_length=64)),
                ('buttons', models.IntegerField(blank=True, default=0)),
                ('fringers', models.IntegerField(blank=True, default=0)),
                ('box_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='program.BoxOffice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=program.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='show',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=program.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='venue',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=program.models.get_image_filename),
        ),
    ]
