# Generated by Django 2.0.2 on 2018-04-08 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_auto_20180407_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boxofficesale',
            old_name='user',
            new_name='sold_by',
        ),
    ]
