# Generated by Django 2.0.4 on 2018-04-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20180408_1340'),
        ('program', '0012_auto_20180408_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxofficesale',
            name='box_office',
        ),
        migrations.RemoveField(
            model_name='boxofficesale',
            name='sold_by',
        ),
        migrations.DeleteModel(
            name='BoxOfficeSale',
        ),
    ]
