# Generated by Django 2.0.4 on 2018-04-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0013_auto_20180408_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='warning',
        ),
        migrations.AddField(
            model_name='show',
            name='genre_display',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='show',
            name='has_warnings',
            field=models.BooleanField(default=False),
        ),
    ]
