# Generated by Django 2.0.4 on 2018-05-09 05:36

from django.db import migrations, models
import program.models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0014_auto_20180412_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['order_index', 'name']},
        ),
        migrations.AddField(
            model_name='venue',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_searchable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='order_index',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='sponsor',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='venue',
            name='sponsor_image',
            field=models.ImageField(blank=True, default='', upload_to=program.models.get_image_filename),
        ),
        migrations.AddField(
            model_name='venue',
            name='sponsor_url',
            field=models.URLField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='venue',
            name='url',
            field=models.URLField(blank=True, default='', max_length=128),
        ),
    ]
