# Generated by Django 2.0.4 on 2018-05-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0015_auto_20180509_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='sponsor_background',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='venue',
            name='sponsor_message',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
