# Generated by Django 2.0.4 on 2018-05-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0016_auto_20180509_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='sponsor',
            new_name='sponsor_name',
        ),
    ]
