# Generated by Django 2.0.4 on 2018-05-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0017_auto_20180509_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='sponsor_color',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
