# Generated by Django 2.0.4 on 2018-05-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0018_venue_sponsor_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['map_index', 'name']},
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='order_index',
            new_name='map_index',
        ),
        migrations.AddField(
            model_name='show',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
