# Generated by Django 2.0.4 on 2018-05-28 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0019_auto_20180521_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='replaced_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_for', to='program.Show'),
        ),
    ]
