# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 13:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address1', models.CharField(blank=True, default='', max_length=64)),
                ('address2', models.CharField(blank=True, default='', max_length=64)),
                ('city', models.CharField(blank=True, default='', max_length=32)),
                ('post_code', models.CharField(blank=True, default='', max_length=10)),
                ('telno', models.CharField(blank=True, default='', max_length=32)),
            ],
        ),
    ]
