# Generated by Django 2.0.5 on 2018-06-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180608_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_survey',
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='User can access system administration functions.', verbose_name='system admin'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_volunteer',
            field=models.BooleanField(default=False, help_text='User can access volunteer functions.', verbose_name='volunteer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='User can administer this site.', verbose_name='site admin'),
        ),
    ]
