# Generated by Django 2.0.4 on 2018-04-09 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxoffice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxofficesale',
            name='box_office',
        ),
        migrations.RemoveField(
            model_name='boxofficesale',
            name='sold_by',
        ),
        migrations.RemoveField(
            model_name='boxofficeticket',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='boxofficeticket',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='boxofficeticket',
            name='ticket_type',
        ),
        migrations.DeleteModel(
            name='BoxOfficeSale',
        ),
        migrations.DeleteModel(
            name='BoxOfficeTicket',
        ),
    ]
