# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 13:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_auto_20170805_0821'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='catalog.Performance')),
            ],
        ),
        migrations.CreateModel(
            name='TicketSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('box_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_sales', to='tickets.BoxOffice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4)),
                ('fringers', models.PositiveIntegerField(blank=True, default=0)),
                ('is_public', models.BooleanField(default=False)),
                ('rules', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='ticketitem',
            name='ticket_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tickets.TicketSale'),
        ),
        migrations.AddField(
            model_name='ticketitem',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.TicketType'),
        ),
    ]
