# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 14:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentFringer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('description', models.CharField(max_length=32)),
                ('quantity', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticketitem',
            name='ticket_type',
        ),
        migrations.AddField(
            model_name='boxoffice',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketitem',
            name='description',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickettype',
            name='is_fringer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='frequentfringer',
            name='box_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fringers', to='tickets.BoxOffice'),
        ),
        migrations.AddField(
            model_name='frequentfringer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fringers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketitem',
            name='fringers',
            field=models.ManyToManyField(related_name='tickets', to='tickets.FrequentFringer'),
        ),
    ]
