# Generated by Django 2.0.2 on 2018-02-28 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20180224_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fringer',
            name='box_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fringers', to='program.BoxOffice'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='box_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='program.BoxOffice'),
        ),
        migrations.DeleteModel(
            name='BoxOffice',
        ),
    ]
