# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 06:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0003_auto_20170805_0821'),
        ('tickets', '0002_auto_20170807_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fringer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('description', models.CharField(max_length=32)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=4)),
                ('in_basket', models.DateTimeField(blank=True, null=True)),
                ('box_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fringers', to='tickets.BoxOffice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fringers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FringerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0)),
                ('is_online', models.BooleanField(default=False)),
                ('rules', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('description', models.CharField(max_length=32)),
                ('quantity', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=4)),
                ('in_basket', models.DateTimeField(blank=True, null=True)),
                ('box_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.BoxOffice')),
                ('fringers', models.ManyToManyField(related_name='tickets', to='tickets.Fringer')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='catalog.Performance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='frequentfringer',
            name='box_office',
        ),
        migrations.RemoveField(
            model_name='frequentfringer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticketitem',
            name='fringers',
        ),
        migrations.RemoveField(
            model_name='ticketitem',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='ticketitem',
            name='ticket_sale',
        ),
        migrations.RemoveField(
            model_name='ticketsale',
            name='box_office',
        ),
        migrations.RemoveField(
            model_name='ticketsale',
            name='user',
        ),
        migrations.RenameField(
            model_name='tickettype',
            old_name='is_fringer',
            new_name='is_online',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='is_public',
        ),
        migrations.DeleteModel(
            name='FrequentFringer',
        ),
        migrations.DeleteModel(
            name='TicketItem',
        ),
        migrations.DeleteModel(
            name='TicketSale',
        ),
    ]
