# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20170808_0701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fringertype',
            old_name='quantity',
            new_name='shows',
        ),
        migrations.AddField(
            model_name='fringer',
            name='shows',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
