# Generated by Django 2.0.2 on 2018-02-28 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20180228_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fringer',
            name='box_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fringers', to='program.BoxOffice'),
        ),
    ]
