# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 19:09
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('tickets', '0004_auto_20170808_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='basket', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created', models.DateTimeField(default=datetime.datetime(2017, 8, 10, 20, 8, 50, 329238))),
                ('updated', models.DateTimeField(default=datetime.datetime(2017, 8, 10, 20, 8, 50, 329238))),
            ],
        ),
        migrations.RemoveField(
            model_name='fringer',
            name='in_basket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='fringers',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='in_basket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='quantity',
        ),
        migrations.AddField(
            model_name='ticket',
            name='fringer',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.Fringer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fringer',
            name='basket',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fringers', to='tickets.Basket'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='basket',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.Basket'),
            preserve_default=False,
        ),
    ]
