# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 13:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20170811_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='fringer',
            name='name',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='basket',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 12, 14, 52, 28, 68547)),
        ),
        migrations.AlterField(
            model_name='basket',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 12, 14, 52, 28, 68547)),
        ),
    ]
