# Generated by Django 2.0.4 on 2018-04-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_tickettype_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickettype',
            options={'ordering': ['seqno', 'name']},
        ),
        migrations.AddField(
            model_name='tickettype',
            name='seqno',
            field=models.IntegerField(default=1),
        ),
    ]
