# Generated by Django 2.0.4 on 2018-04-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20180408_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fringer',
            name='box_office',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='box_office_sale',
        ),
    ]
