# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 07:53
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0007_auto_20170812_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boxoffice',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='fringer',
            options={'ordering': ['user', 'name']},
        ),
        migrations.AlterModelOptions(
            name='fringertype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['user', 'performance']},
        ),
        migrations.AlterModelOptions(
            name='tickettype',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='fringers',
        ),
        migrations.AlterField(
            model_name='basket',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 8, 53, 58, 34507)),
        ),
        migrations.AlterField(
            model_name='basket',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 8, 53, 58, 34507)),
        ),
        migrations.AlterField(
            model_name='fringer',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='fringer',
            unique_together=set([('user', 'name')]),
        ),
    ]
