# Generated by Django 2.0.4 on 2018-04-09 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0013_auto_20180408_1340'),
        ('tickets', '0008_auto_20180408_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxOfficeSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.CharField(max_length=64)),
                ('buttons', models.IntegerField(blank=True, default=0)),
                ('fringers', models.IntegerField(blank=True, default=0)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('box_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='program.BoxOffice')),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.BoxOfficeSale'),
        ),
    ]
