# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 15:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20170818_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 22, 16, 55, 26, 384551)),
        ),
        migrations.AlterField(
            model_name='basket',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 22, 16, 55, 26, 384551)),
        ),
    ]
