# Generated by Django 2.0.4 on 2018-04-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20180409_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxofficesale',
            name='customer',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
