# Generated by Django 2.0.4 on 2018-04-12 15:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0013_auto_20180408_1340'),
        ('tickets', '0010_auto_20180411_0623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoxOfficeSale',
            new_name='Sale',
        ),
    ]
