# Generated by Django 2.0.4 on 2018-04-12 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_auto_20180412_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fringer',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='fringers',
        ),
        migrations.AddField(
            model_name='fringer',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fringers', to='tickets.Sale'),
        ),
    ]
