# Generated by Django 2.0.4 on 2018-04-14 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_auto_20180412_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='box_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='program.BoxOffice'),
        ),
    ]
