# Generated by Django 2.0.4 on 2018-04-14 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_auto_20180414_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sold_by',
            new_name='user',
        ),
    ]
