# Generated by Django 2.0.5 on 2018-06-11 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0021_show_is_suspended'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0016_sale_stripe_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.CharField(blank=True, default='', max_length=64)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4)),
                ('reason', models.TextField()),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('box_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='program.BoxOffice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.Refund'),
        ),
    ]
