# Generated by Django 2.0.5 on 2018-06-11 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_auto_20180611_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.Refund'),
        ),
    ]
