# Generated by Django 2.0.5 on 2018-06-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_auto_20180611_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
    ]
