# Generated by Django 2.0.5 on 2018-06-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_sale_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='stripe_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
    ]
