# Generated by Django 2.0.5 on 2018-06-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_auto_20180617_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
