# Generated by Django 2.0.5 on 2018-06-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_auto_20180620_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
    ]
